### ISSUE TITLE
MBT - Make local games available for event/workshops

### ISSUE THREAD

**Issue by Raytesnel** [OrdinaNederland/robotics-workshop#12]
### Use case:
Several events are coming up soon, and we would like to showcase the Robotics community. For this purpose, we have come up with two games that we have used at previous events. However, we encountered several problems at these events. This feature is intended to make these two games more robust, so that we can run events more easily and beautifully.

**Pop the balloon:**
The first game is quite simple, where a balloon is attached to the back of the robot and a needle at the front. The goal is to pop the other team's balloon and receive your prize. We also have the feature where the robot can live stream its vision to a front-end. Unfortunately, this is not working as reliably as it should be.

**I Spy with my little eye:**
The other game has different functionalities. The robot must search for various images and capture them to earn points. The robot must do this within a certain amount of time.

**User stories:**

- [ ] [ Robot snapshot gamemode ](https://github.com/OrdinaNederland/robotics-workshop/issues/9)
- [ ] [Make the full system locally ](https://github.com/OrdinaNederland/robotics-workshop/issues/10)
- [ ] [Frontend local games](https://github.com/OrdinaNederland/robotics-workshop/issues/11)
- [ ] [Improve game manager back-end](https://github.com/OrdinaNederland/robotics-workshop/issues/20)
